apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgCwwoefk2rffn8byZJx6lqdnJWjIWNoZnRUh+MWLeHlrWd4HeqLCOkI2L4Hsi6KQoiZjyZPdoeiveDjjgNcjh7mISc9hKBMWNnEwXs1sz0QVqmHmZYh+w33n4jUk3Db9sF4maJNAXevVFlxqLNylgoIZ7ZFe8KqyilchrSHSLyYRlzHlWjIxDfYUoQ3QvGqgD2HY4JOu25SfHdKGumTI+le5BoXiYdiktwKxln/EHYlRYdi632khY93yYFdoHQ/0IbSMi7ENedQIAOOlMB3TvTyjzyrcBMzZ1jJgLzQO0IS6QK5xC14+LKpge3PGFv5eUbjLOZP3xgOyspQAkB5eQFfrxYXPVHQrwKpExlUFgBbDnWiqlBRpzq5CB6ZLlaFx4Nj5VgVkUFvCmkmkSn+v4yMihk520oaOcHOMQVa13D49RIr5DdhvR87amniYhNN/ZYyOV1QPuuhRkY7ZRFCIA/PSTzEcAOzhAoO/2CroXlkAH+dFzsz78ngsVzf7V2LNkkeFts81lk//LzjnWzUgTq7XlBFuuDK2OWvQQ3ZLb7uZ5fCNXhOnrpYId7Pwz46u+spJy5m+S1nckldAZqZlruo4HrD/aLLZwWZooGDWP00WrmAN8BffeJyqYKkhKEovF5q4kTYPcdGBOg1lHJWm3uH7op4nBA5blCMswa4WVENcnn4qpFI9QuPARMnu2SDQt+GuCgXGQ2/EJ8ccj7dQLR0hIzUKX4gfisMnuG3flPeeoFAkWNnbWsCf+i144pu0ikouharsoqTLbAN+7RoNrxxMrF2En5cJA5ntrTdZVqsBYtQomAhuyk6xPA3A10XChnQ6VlvIn6h2Bwtkzib+MdwWmaUDi28m9bozZYO7PsjYuzj21nHmBD6kWm23SpJWhlFG3DfDKapBSWEagZEMsquo1MMuJCoNzleLoJE3JUoPY4Oa9HKb6AYo5vrXwPvANSt4A7N+mlAgQ==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson