apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgAwr1lz8UmFiyGw/t2suXyWrzRQBkGQIvUwwKK4oYLrkQWX8nohwWHH+mS7trIURmqyRmJ3bZKip1PkbSu5p57i+Rp2u7KnczeR7Bm0STpbd1w8qE0Gmpmy8FLWB2ThbkornauNxp7ptHN28PAMhoIYcBXwSmsYHGZInUMFUIpIU+5GVE3yduBhBnjHj528cQOHrp/y37mNyzAK/pNvXO49j2i1hPJl3sEQXNxG3a/Wg+7BodXgCF7bpXQXXkGkGpT5/TMbj10Zz7+ogCwKv1QvASedN5QGp/KSMy2vhkJD9hQ+ob/YLCF94TuHx9xPtBSQktpD7QYsNINdmic0PRZhT1fvv8zRuCEmDyUCM4KvrAVea9T3w77iTOIHU8xPEjfdiji49tiibZDyJIdgUZracZtYAiQ98+0s5VfVyFXhZcSQmfPHjXz3azHYt1z2VApXt+7nSA9mTndWOD+CLcJhmpPUMsTupEvCrAxgSL5jvjE1V7q1SUJB6q3ARMDWB5ND6nilh+Wy3V+A3G6SVeFRuWRyt2UPmPkeX7O+wpBqJ9wbd/d2u3tBu/mXkB/V6KZX76iwYJATI7o1kEDmgjqA9h2fgTP4TB59MYYXZT6Go+ySoFM20TaT0TIcDmyrx6iH8RHSWmUEnrM/AJtytEWBK4Q9X203c2Vwzbak55S3f6iEVB/yuX51DIPN111Izmqqu7LmTtwXBDMddmv6IQWdcwAM96Bb5EjfG4DAcNzZZIKYPZuIMXpYWmOHzDTWihVK1mulOHfkSebGRjz0wUmcjEeg5GVqC7gshPSIM5Pn5Jn2m92oCLmdmHtyOHpByYkl3sqRqzvWvHSBkKDip1i89rIc33G3O/EcCkzV34pFMCsOT01HlVoU9kmg9TTs19yTepi1A5KpNf1al15pQlZ40tmcVblNqchdJc6VCxlKO49NQ/5oFViVK52hmXkGgATV9anZX87wWA==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson