apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgBKvxxbi6SRaM0NG4dwDEYlyTvhP7JPMkrAD4RDmAqyLZZJ85DcF7HYMUNfi5aNEQewGIgr8rNrYN4uxm6T34fyhoJ7yhHTEcIDWMjv3FJ90I0fOx5JP5BHj4ZPG7pti/AdysX6fqAg1GlVnjbu9ZuQ0u0s7NizQnV0XB8G5YcqgFfWhTkeI9QqlyX+icDUa6nGb9SAP6LnPfd69wrqylj1GfBqCpNqqGVHZtqob/XDMWRnV8dk1HL3mtF/K1wMwYl50L/pNnobeviCC54DyaiH6WDbm4Q4YlWxnCwPXxCJ/Rb1znt4CWXKCP/D69kuGZv6I34l5Xegk7zKohc24lfiw6zz0ARjvvfXgb2t0QmRAq/6ev75HYScAzpsIrz9JCMiKjoszF+f7d13qA3m6iAbcx+n9xymrTF92IfTVhUvUC5M6QRDJxFIizuZLVQDUMeAf0S4/F/dSRGo834OZef8XwEvabYhrUAomDZXu2XiZKzQvLF8JOLS//ka+RDeB2/Pvpd0dCWqmdT7xgoJtoIk2kwEyTmKljr6THablf029iuyE40GOtBvWn5dlPMJIzprWgKnsAD8/V1PU8mgL0UViTAFKXXK10i6bsyJAGF/sQVvWdmeL9vFlYbgevZAlXTNL2vEEJ/JVarkAITtUkfycXmKEQrtdPLp+5+esiHfQ/OD1OcnZH2HuG63ytWNw5ww+wqA7pEtE2rxp+ic+nkIYmeW1i8RjXARw9pxbn2Zd0ntSqvDkX0QNNcY4dKmQe2kXtI/Te/WXwii3IqzwhwavwlFwphl5hPFIhEPDjWpvfUB4TjB6GT+67/DFVhRtLX+tvOR/UOGFgKC+gJrZHACdOoKpRD2kWR533/4fn6+F5hIheZxw6ad+A/oe9RilQs/+Ids7uo0FHxr7jTW+n5SlweI9oYR3lgViL5lFrBelEfiLL8ZLDVOATj5LfYJaVApt3zHacbpaw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson