apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgC8qBpqwiNGduzyTPLArehDLC+Ntr73RT6GqRThnfyk97D9lGkgN/TGCekBP3EG//jk5UM39lS5bSDpka80/pE93ZCEqMw8Mj5wLM4CXyQ6BwalNL0yd5ycwfxYmnML3DpKNM5gYU6/mcytVJlFYx+mgGEY+N+ky8joDJHDRbCriomG+pKOHf5YEW5IL2c/lIh2yEGFf/ksrMaq4uab5/eI5gmRpdLcHUymbQ7P4FZazImJVRIlrFtRIEjNt5PS0sVYQG0PYgkZiJSVkw9Mt24jxHJKRkN9PddWQXXinkdhf+Wdc/OIMWS2GA8GDK+0nRLhXnJrq/eDNPQO5RjqQgbyJD1IRMfpSvo52w4PQFs+LmnWV2T87abqcOthhYY8+n7LKiA7o6A7TF8bhvRhmBbHMzlC+Ru3OPhEaiKgMxUconb0LUHYPoCrP1wEUVMyprFqYZQJFpI5Fc4EXFoUxGkI1qUqx+ekXHmZD8fAMxGQgI4MaqF1x2g0fhNx5wxQH37QdpY5mLNVIbfTi6H1iex+FOmGPS/T3NayLViDlaYVzIclWa4PQZp9S7I1Eji/mRu7WF/lp5IBbiz2Yf0bGii2FGujuZxlPX+zcMQzz4qAJp6gHpukyI1jCXTMYC9/hrFqwvqaolpIpPoT9LonoQFSBMOsVv6h0ZcoEAdpoqYEEVg0afo/72DU7/nrt8m7I+GBTvhrcjn+2ScTSIvUQ6H3FdS0Jm07jnm4aum2fH9T29hOlJvuhJHXYAmfvJVRqsy0Rii9GbfnpuH1QkvNEBi71L4piMvNbTM05V4kiGDpjc6hq6fYebshCfPY/B7tSO/e0GdhRfY+zufAR2jqByt73WF3ZNrzrCAn6DU+OLsqz+VjNY7v3Ehnh/bXFwR5Ee49tye8nDImv9bKh4D9+FscboP/rZvH/48TpM3PJeu8swojMvY9E4wpPGiPTBSCGiAf68hDSmZTVg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson