apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgAVm5tRwXWOK/9Hzt3fuQjamcYx3HXVxLrUgtFA0b/eGqpnhgDolBLO2XNg+/zHDLjHNiA9VG/9JPa+SOThMnlKdV2jVsgpaoCxFJ0IqD0HtmB9h95BBH8Azpd85ufIdorYwnkJ7oVIcv7DO45FHzkQz93rhRDChzOh5iUwET449pxguXZJ4PEsItppSooFvVLuWBXmGRtiAcw5EYzthiGjOt7ro1uM1eSCPEYwVlz9Y0Mces4NDykPed5TB4u6p08+k5qKpgJMxNylxL5A0EuYLxZfA284AzrkwfwK6Q6Htzhb0JDH37/DO1nlvU8G7HVn5rNrL7ljVJL/of2EobBHeBa06fjKa9jExCjJHkRRN30drLmmH4Uvsf4BKa3XTz3kKpsLK27CsQMnFly4SsmRElQr3AfAwD3+onsSHPaB5dX5CvwmbNeOMOoLaxQ2Ln+CEu7QbrVXQ0XQzjB8Uisd7ann2WEsnTmCmjNlhMz6ll1yB4bwNygJrwnSchmqtJxCOqQnOEZGZA5wotLaNYZCd7sPhGyFeQ1GLuko+P3lP6nwhq93IObSLa0suYIZ8JSivK/TPBF+XMAZrEt7G6S30Ps+KERvK2RflwXsGfI/llf+hvHYCCAx77o/Y/jgWwC/K/sHfwrn8ShLIdCA5o45CzUoT0fl/oK6shxottS8GJx/y3wlCw2Y1vuYZuofuPtmC1e6wci0B3usp7L+HYHn8TAPansiiPneN9CJMBLar3VwqQ7KcqSUfA0UgR66ddCPW0+alwP5iTCcA1azi67DeokC2WVDWJJtsLfRoryHd9gvg1urXmOuxWSRrQzxr4EqH9OsQXV/5rIJFr38jNs/CDWWMkWMLKjAalIpyR+mkz+0bDi54uT4dtnmUb6kIWvRduRJyqq9baq9lkZgYC5DPeDG3JN5FG23id1Zcd8r/mpD0WF3hFNCfx0SzCRiVBU84ofMnAGXVw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson