apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgDPjPP/4bkw9HljaQHUhNP5Lf3Q4NipGVsSmCipmso/d0YDok5enCcQmhSWF0ip85y53Fzd5VEDfY0a8fU4thWCbfyLWld9xrwFgxgP1aXiDNzHiGceubZ3v9Uskaw8gJ3hN7ifmyne607NFHxDj9PvUzCJcfnYm9wlF+gro9R0aGdQlW9ka3+lMjSJ17W6npdctzwMNJLpjXoNjlh+hZVJ/tjz49Qta/JjBn0W9+PQb5e0ClFGJvq79t67kwpsCySuiKwEENqchqES1He9oIllEMW6ZQxxZGMXnt+/DKCRRy4ftt6gS5LLPRBPr/rKiaT8lmcFk3xjfJZJy9an3YvhiNrwTMc6+rQYZ1KkcWgznGq929oqqKzgc+8Sgsxklhkv/92Vph34GPjA75uav5unoHlKowXwWa/t9nTECM7gyI0gKp3CgI5BEbXnKIFfsNo8/2kbWQpYW06omEqEPJM+nC2txoxyRXSa/IjWSxbT2I0qbaUTob8wxYa5N+EIyjxjvqbZdp1NBdOB7iWoXZQ+FcsrefsYZw1kIvv0oeQ/mxdAReqQHrqpcoH2T3H+V6oUzb9ZELSR88KfhT0FDwFu5nxZwvX53UnZer22wUp1x36lcAiwst0VZIgny4X+/s6fkksBLe/VmqxaWg4/T467aA8EXbfFjoQEtb6AtSUzsUb9+OgxbCD73wxgMuScwSt8Sj35U+azSyQ26pOGy8zA4KF8gBj3SixGIExs35AdK8Tg75O/gWHFJOS6kzs5q2Qhh2S3aswc/bnqstiope86WeTPae05jBBw4ibPZw8i3TpP51vs//wdXSovKZuiVjxMk2ZUQqkhK8Q7utwgiXiLJVa1nuwBMvKSAfgBaINc7Ycpp4bOlKo2h4Uys8ynl5+9JF0tGxZ0prBC1FyHqAM+TMC1Ktq2VDaVGscHKpOBHXvt6KdlrFciznAV3VgMsy63PrYBM0CKk1MmqM9A7Y6iBvPtWf24qb2uq5tL9QigLyiCqGuaHwqxK57bvU06ycPlz0NkN86TyYbhQIERehjKoEaN5HX11AzkLcLH
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson