apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgA9dXhQK1P6dk7hM84fs98bGc9hApbTwdpMJbma3Cvi+xItZYeQOOxo/YErgjwXnhx1fEp8wFYbVyldyW1/4ehCUTZ9MROJt6cKEJ0M/MCCZKwlWRyA3DcBgEQPRN/5cVOZjsPY93guSVupGKFKmR2pxcG21j1nRdit2FGze9UKiyiS9SPELunTxvOjFxxYx6QaYm/o+hFboapqUdqCM4jzA6chQjbVLjjs4FYgg4bzo5lCE2SlFiylEZk7qeDfuIfb2hE90Rvp+F6CMjWV99NqinZIfQWhpEuvsH01/lbQdZokkpbU9vjl4kkGkPUPWo5mvLwpAPeput+wT3emqAz4kk9FtyGavTAOr/wX0JjSN76OTPUhEn8M3FpfV0gbcmAlyEPRzedZrJg5o0YHyk9oTJq5zoKi4uWSsGwQorY52XD8uSFZ7LDd+oZJcAC1tqGECZvI2x+qpS6elWvp5jIHIPJ0LzgOhpiZmiwWvHcAw3XfAhEYQlVTLQCmeZN80JDzWMutHk6UJ7n+25+s7jjGr/Yb+rvrycp4qbeB9yRABgv6pFZyTVYEpLIkFjjjTucjZRZQ7skUcEwrm9DSQkbvt2S4sZfz3zHPtViPnRwkmHO/FXc25ZB4jgFX/+mZ8CkBTv5XrcXjBYMHIcGqvW3bV7Te1GH3I/I4XZ7lh9nPay6YQaNuERsTpUgb953plPDHkW0PiU/c4lRGuiqisUcl7VFzSdqrwG2XzmUtTaTUgz+QlqdZnNTykc94RRzG13KqhhOxmgB1ePg+gVQkRPYNiCJDBVBZU3ewEp0tJGxbePX+EnzJ1g5iK9Gt/xb/HcL4fsJq+QQMK7yaBNRXN0vErezzUH/Z//HDlcZXuY6X2uBzJDHqMyfi6PvFxrn5GMw+rNlKTkc4aXfzIVsHNZfJ2vcl6CC1wy1tsBNKoqN65P2FX+QMyg8Rf1HGMJ8ksqlpX+U47XsXjg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson