apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgBlch45wC3YD9Y50G7lE22v8IiM19YoK7DjUdSqxSD4be+sycTd7zfH5KBAGZQ1iNQNbGvXdZWsa0Cinh7K9h+Ecg/CZkdU4uaJccW/kwixIZzdXgLW5DrtXI9IVUi4Fgka31q185Q2qVKat2GZPOT2Dk5/RJRL4SuaORo2lpc8a0kK3jDSDzh0LPYtTTfdxKITRxwNre+DI2TBOhzF8EcvolDqpD3pnkl2r6USl2LHzk6TcDbQ/uSKb6GRBxm3z7m117WwJ6yUchXMlAyqhCjMSzr2AdfkAWkpNIG4EbOtk6oRdU/nWjURwdEJEt9881eYbfTN3h2Dubb+SKBcmf9lG9uPPl/o9q6NpevZqfBKMAVZUFI5/tZuhm/dtEWQpmHa/UOdGX8iX+w6h0LKZTCXWdcXK3dpaUbHkLk0doKZo/fbwuE+a9Ge0qQji20hIPN6+gE3oEVgNeVUptKGdi6/Lhbl+6fngZzs3VmaPTovl1RFgUaCSibwcZKxNDioRFWdr3EUO5lrgJvuO69andPs+WP2aihXyg1UXPURZumWu7JPMIK8a1B/m1dwcNCgz99aDT6lpCJdDwsKYY4a032J78Qb5PtJAjEM4p48ECRe6b2PqXzp+AilWEq8JlOeWJtFvB0OsOLmC5hsytK6YfqBpKs6cpSGA9b4B2HKlhCp4UldG+QBuQEeiXUuBUlhbFOPXhe2Me02Ut9t/67WV7rjjeod2zzZLJ16skcS0thuNVz5kMXJzuE3sXmnZIrjMn2wh+ZVcXlIJQHBc2OxOZJ9VK4eJOvy0IJtLptuudtN9tDAPI4qt4FOFZrbWovQDePPLlb0AIV3elSq6HW4E1SJtLhRRcP0m8bLb1xK2s0bHoCmS9DZjXV4eI9cgj7ICYm/oF7f7gqskFSo8M2Co6eFui3bBFQ+oS1eYpMYVOF4krKjVr1kIu1v2XkWQmo5LcRcae3U7LXdPtXVKExyxAiTh4wV5FxV2zVOVBuhyd/XY8I4lWKcG6R6RPreqDicLz/D/l19dLHdXWheQiQrrU3RkdWRSVxmgry7Yl3O
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson