apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgBSCEUEGJih/tiMxuO86dEGCDx5+ifzcx6ue7lsSo0JRWpGEqAnmH550YOx1cuXxmMVVUhHDj0G2kRKxg7IUNS+rLD0UoLD5Asbzd8iw8YEHx8Vwc3st9rwnC7XOzljxzJyXESMk6zFQkmnEFunmu/9kh69604/dIO7ZWNH88pqeeNCUQVq+LFoRH+FUYxgY97SCT5wb2PgIGq0VqPsYSXvXzkAZJDSyT7Fnbeque/KKKvXkXEn2Vf9lniJSpUIK/5PL02QwWdGUABRnEnMG5LN2nQo7EwHpJ4dIhJXMCq+D04Tz6tZaNbNXps1IiGIKSdhoijwW+MfeIXo3KtmkIs3bYU/YUuKWY232umwGfKXCBs+qLymv+nEkqG63UhICEKYwtG4a8pbOZFAYb8qU1KHLWDdns7LbBtJQhd1B19hwKZ67joY/SXZ7yZVMLSO8w1VFNUXEi0OZXzNvQElCQZmGRZQfss6kYyM84BjXoOzaGSSI+tmOmsM3mbCWcxrZUf8lFnSiLOuqSnZgX/YHci/hNIrBDr77E841kuITgt3u5HbQNEbUut6uFqE8oRrSAgMv/H/fEPITM0M/Yw8roxIvMRAig5FUXEJbWhtID9zQHl2ttw3wbyWeXU7HEqKRHC73A/QrVBsOl4TfCE4DdGDyhyy6TlSdRHSXwznwok/UobX03fkFg9mW3PnwY5vIUqGy19r0GJD0pTiXb2mEYKiENJSUN5OCdtITjyD5S7s0D6S/mx/6EI3rAzMKRq5u5wLp5j2D3D4KNuRBNdtSnjJOPLun5Jpo09I9/SBSFRUzX5yYbl0t58K6hJv9pJng48kel2ERrzulKOkOtTK4lOgnt0wZGegYtxx7PmgEW+DSC7ESEMnFUH2xlTVX9ONE4AvoI29kv1RW/kG64goDh9zzN0Twx75JQpz8oZ8yG07P7KT/GoP67RNhR3EonvJmhPBvXkeOBdrDw==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson