apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: learn-rails
spec:
  encryptedData:
    .dockerconfigjson: AgA8Frabze9GudSBBtFpjzgTnIyQifEaddX67CFtKQ3pBd+pWsRCdI/iSJWxdChm+sduxevluOQi3it8hQUwbMhGqEg6ZpADc6bACvjB876E/1pQEm+fxZ44qibt6GUFmgCtbKzKH5mfOQbQsqy6BSQUbWomqTqcxcxohEqCxWcnYYwTGx4hJggyPuWhxUPMshvTRkA8J1ziQnCcn0W/AyVQIyJMFzClWAtwa/grFkzXwcaSOtDp45ctfPYHRr6XwxiO0J3fTytGPR1pz9YnQcc1LZFId/CuthvPkszMqpiuQyu4KVlcUdQx6vTAGy1CpVdDDgXFeoG6m7oVHx58NBzIOzB5QM1Cd/Za8Vi1r69tisT0t7jdSRnDfvZyy57Y1wn1b5r6UW+Kn107A65W9Sw5fAGUiBAxSGjf7bjtIj62CiCdXrpGb0jFMXeCQ/4/6QzqPDdwV2gukbmg1crbFhtWhZcFvjfUGBEnTopPKYZLg/jkfZ7IFm9LHNe3O7KyE6wwgVlC3o7tmMaUtQHuKJiIN7jI3ChvZuDIY5ns0SggswL8PqPiB6QbA3w2Qp/d4Zc8bh/zveSPviNNLY5wal46Eoivn3V+fgb5wUSXM17/un2SVMAtr0byjnMHY1NxFDurAOM+Je8DWvt0mCcfxFMle5xxbwvt6E91E1HRPOtHcXpY3ZdANxYaAF6n21ZF/ytiEGJT3EZf4hXav0fw8Ahtz5202KnMCpOqRxPC1+qievOBbtn1x8CgAkFBZhs+/EgGBFiH95R4Uqa/R4hFXRSe2+T6D3sDfDzre59ZziFNjCSLO/mF3c9tkPszrSMAP2WY72pkyjIvOhu5SUU+lfzN7PodtUNyvIpGqU65rCl0ywLJJMR1kK8Nou6fMLJd7DZdC1eSW/hs1oNzQy7igTFuc+bLwYaI9ZVtl5UFb3D8r1zdiremsXCke1UKVmHG3fxPsUF9qpyHfg==
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: learn-rails
    type: kubernetes.io/dockerconfigjson