apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-production-uri  
spec:
  encryptedData:
    postgres_production_uri: AgDLR9UYihK6coufRcSK7eEwN2jocHr57nm9kK70bQoQtWUL+5f+OVr7Ulq+nuYTp5K37C+UX+Mb77/nKngVpnqG909qA9Sb6mJBh5XWGzbYVNdxutUU0OLLXyX3+OjbxMZzJhDtbEZZde/NF3nvA4QsOYTySbe31qY/q7ZlFK+CO/NPDmtq6T//WQlQj5kLDhop97Jk694OIhN+1lEql/OH7Hrh2YEpVFQrYVANJIjJcxmMO5BcK4bQ6GhQcVGhyv5SW7bKCRMtspYAR/oAODYkK2Zbp7fcMBmkmVCvWxbztr3CCTyJtiL2WDBBkizNCdTIEUorbiQu69qYAA0AMAQyOg4hJbfeVcYycxKmAk3qgMoGeJCS/7QX9VP3wtGPQuSg9EjmVrdkN5kX12F2jwpNHJJiGX7eCMlz/pmp7JgKoDVtv6oWoCyVxD6h6uB7IQK99gBOLIJXnv7TKrMGP960VnTSwggJKzHmvsHi6GS5ThVZgOpA3wYm8WzsVddXceMQ8LPIDQ97YTIbuGkCAMXwsnFf0Cfuk8XwEsmyrNlspRlfboWyjE4DmoMvxf1T4TMxw9xBd1Ifoqfd0mbTLeU/sZ/iJgOObbuXmTRLEjRSV6ELdjjFQvu5sA9+DnjXXx4dm/dqX0/1Zos05arpSSNT/7Ygp5aTWBZMNV1LpkhPSdoO42zbOIEYraCdDeKYWQSQDf7NrI0m0NrEKZ+Rn6G0dJb+jYBLCTs8fwhQB0T6pSeWYyvYRpxz+aSck7Gq53FQjlWUSS6Gq8gkdCNlwSngd/dqB+SFEkq0XA695wLhYL0h5sdd2WYHJA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-production-uri
    type: Opaque