apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-production-uri  
spec:
  encryptedData:
    postgres_production_uri: AgAWrS82inFojJXqtkRlzZ/etvuS9A3OTW8YOOXCJSgmXt7b5MvIrEFivU+vcmEnGXKuMegaWXSnlchJzaNu9QFNmg/HpZ9r0GiQfWcFeal9HFbezKv2WBSfmZ9nzt5X1+nLPOcA/yl7WYmlglD0enAcEDV/a1kGginT+eElCmTxrRb4orLYdP1mK7WHdCyV2NsITQHXEZZ5b0R9Gn/lAesbMWfyRESRSUnVZBN6zBmW9+CfLqZLWR+gLOJaWzwFiThLyT3BK0m0KWihBJJWkXyHXytD0Mln7ijJQfNmBT0qY57vluTWphaV/YociDyAAGhrjL3/zdFCyrWxLR9q54xyXXliPV6kdakbKkX66eaQKx93kncBQ0yzI//q0+lYK9pJgZicFmeEycqN3S6hHr5ILyD9UJhpy8kgi6+GkB3kh9VWFPcGMABGYxOeZNIcDLx0//ZBgaiIkSRWGqPDqkE3dM/6y+P7t48XCx//SPEvAqyXgN/G3gq+JpRnNTYW0WbC63qCCl2+beNYG8bsS+StneEfJZErGuzP8W3J/ffscTam7M33MVNqLOAZnOr+4bYAFEoPYX1RPIQknDc34I31aiaXYRlVGYg/Kfoo+/M/JNm+V/4R8i4Z++s3/LG0YVlCJQPJjk+K+wA4EC/PCVEmsFlI1NwNXkJVGAFMqXUzaArLaOKa8LkE8mizx6QrUAJf+IamrprVh9ao64FAvwA/dW33+1wZvCDyqKTDyY0p+r4fWKkbLy8/PCyNGmOgEsQgSiB2U8caf/UOxU8nmo9azRkXETp01yEzssLPkrOmBVRAUqPVJjdQQg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-production-uri
    type: Opaque