apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-production-uri  
spec:
  encryptedData:
    postgres_production_uri: AgAu2n8uZXZEeWEuuhJ/x9H5s1J8fNfQ0PXxzCbOfM4UldcKsGuU+PQwUEw7Nbka7Ra/5lRpoLge9+ZK1Yzfg33yY0IvCJiKoi+B/apeCD/ijcYgHiPgFkSw/0GK9m2y1MAPPlCqfc9huFdDjbBFBx93A7Y/D5BOqp9LtJRyBU6ok4nIei9snZb1QRR/DyovN+qnI6UCjiocDZVWlfJRJVQwm3ij2MbLCeyo3Q6WXGwj7kXjzKoJ4WyQQQSo3nh4dkdQJcG1lxtmU5jk9p55mal7gPLB8RKCY96MJJr9QC1uS9XUwu/klomZlXNbZzY+SLcOixY4yA24cRGpqgDVxTwALLH9TOO2fCseCAezQZdrp9N4+le/WjnViJNT7VmdZ14Y8hObuuuQT/3rMuCqB0cX50Vxc6NdMZ00DtAy4g2K5WBWw/aFMdw10J/eWCJ3aleUWzjTQwCAh71QoiG6pKhwG+nKFO5CCNQbBiAFZn1SugmGAgmPmRZ4A67rffXbUPFicqehpfHHN3xgHNmwe1C9ziHfobzvDIVyfHrbnIBXF15C81rOxSmll2LhZHXV1h3Hy6IRU99wD0iC2ZcqTc4s+J8yqAouQADhl7FNwi7U/OvrgAeNghDVC1IGTOpNf459KsVaE9Qerf2KxUsCcd9tOyRbckjf/G+umJxhVJATcqI/T64a8UebOHb77ylvqHdF0vWYeUyjj9h6E2JRygNLrxJU2+qg80iJk5r8iMdVjreR4LimE1UVyEMgUMK8MeBB0Wsz17vzXFreqMtRgzhPF7AA9vi1xPQxtYYyZEPH3NjQysep+jaEmQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-production-uri
    type: Opaque