apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rails-master-key  
spec:
  encryptedData:
    rails_master_key: AgBgYwj9eXEJ6V2ipz4D0TyoLBege47UM+Zz5mUxgYUMJ38iXF1E+hPj+IscbJ53lBdk4hxv0O29S7j3gjPP1hJEkvLrFadtyFjIn4lqmjDB4PWoVGA4OMBQctWfSEUyaHtelOYq5iODn3+rFmTSRPOPbLz5o3AqoVL2MsjjyM9yqbtcIH3rjRthjieuoigayNms3qwDDCnXTNSR1gFDuXRbDCCbzvR2Q9cawBci1l5YEz0bNUwsmMYdCTGCK5f80muIDTNzhyqfaDXw46arBIuzul6yEF/Y4cJrMdkaZwe1GvFw3IXRxnV9i/VvlKmPGtmP9Sz2LQQiiLxHEVUBuThjQ8tEGzwV8P6lUcrnvS6Drg7D0EpVJ5q/OAi1fEEi1B5TT2k0olv8CnXBI8aQmHw8t/GrOzPQ9zVCOodOQ7mczwpu5jMe8oAy7pQ9H4H0L1OLjvTTL/egF3gdNSXNJU9wghTf/LazFd6P5A4X4bHnYT0WF81AIEvU3xjX2QkbfBcYOCndEEOXmQJopdXR8s5vKeIEILdOIkMe+Oz4MNFu4CqR4Ooa55JvMmPXVs4C6qhB9qyRLRYpGnpw+rnCvz9D6vBpVvoW3zRxekdOFj5J84trEF9JyWzt9RETk72wMh4xenJxZM5liZ5IOR5g8FyeFttOwRs5tlnycq8z8EwHmIMxiaNUwd15gYNZuWpHJUFZaj3WWCJKDAnHayRHTQKVeGNxz5lRcsfalcmvPqxIfQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rails-master-key 
    type: Opaque