apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rails-master-key  
spec:
  encryptedData:
    rails_master_key: AgAy1qQHz/RPdaY+Fhoxl9IqxKOAxmEcz96UQ55bk4tW64xUKAxhmIfVW3YAnm6vpL8Bu8yssLHQAVFMcKzwThEmTKyTZGzB9CN9SvkRbcrQyuxUlCcuIijD0pN+o/oaS036+YkTJBiOQn8Tpad0CSxvN0/a+ljClYgoAiw9D3e2XOEKE/NBpzCULlJreGMratExc5IbRAv+EdaM9OqTspyhTPYZHCO+3DGM8xbc3JbesPMuOFOc05e6rGG7FhWrVNkKnLmBu4tX9BMbNOu0wypn/k7FzukxFqvyiQlAgTcnGc7haakkI3WIpKu84SzbO8q8dAxQ+I133LiuqFUOs81Q1RhZBfPTmNxQoNVovQmhX1nn8jmIg3SU1RpeqZADjpLcq+4FH6nXcW9ydLurq+duV3qQIhy6vFy6K1fDwAZd8i4Tf+kYvZxYY7YRHU3NmryOJ8LFbmWfpSTwEfFcNjnbyzCtjiGOqqP1T+BVdtj/gZlfd1Yo7t1yvrlsuoSWzoCkJG090GtCBvTK/j2HEBHWtZfGMAo317uy65sRQbO42pBYFmjooeW668sMbNbumkCTqbxrjyOy2MxrdBsELxoQDeIljBj502g5xIQP7dnrE2R5/429O5s5uJvIxJzdamRFkVNRn6BbIXJPUh1jbDXNC1eke5dAC7Wfzk9bvxaq7urgC30eJYQ8AGdRXUppfdULlCnyxSSj29hpZnpw3O5zhtwdPXospUW+qT7DTE8Bow==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rails-master-key 
    type: Opaque