apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rails-master-key  
spec:
  encryptedData:
    rails_master_key: AgAHc4pasrDDYA9w4VpnjfaXCXzU5oeaemq5tKaina+Dub3r2IAQWMQyb2TCycvFDAQdIaB3c1O739NT0LDM58fEajX2uMueJ+EIOxcTrKacBLmIBfIyvHASjb/Mpjzg/oiwGhbGgEh0oqKE1y7GWaXnjRCIFQotmg5KzC4jK+qOzpwogakjUu5BZaRVqrKgIUjzgr6MCMH1gvLacxdPQavVQ3FuYcMT0tx2gFZ7wW1awzAdOk1ED0BBaY/wSBSF+ekP49vWKW/S/su1GtBQ+I31kgF9aclSSXSmCrWcomGR6wfXxCxmI1r7BL1OvXqJtyVBiDXU5+jfAXWMHJyiunWHxxpAKL+toya2HpcW9EAnKS9chLjAR4a/+YLhNjwP8YiKyGZ3PH03uFUlWn9Yqk++m161w5pz1afCxopJ0KbRHftgaelcEctZCTvIL5wcoU55qbytq2vaDY5Oul34z8Juxoxu7sRyXJYo5inABnTfbxjPvbBevsGC/9JLMvtD8Kc0JEWsWrTATp3Cl9eR4ADTe91UcAaP08g8bzH9QA1BPCrUk2AioR3DjA/e5JKBz4PI2qu+fvHKSHE9RtuxkGzVBESACqNDz+1kx2SdBsvaF5crCGO73oMhTobMt2UdUq/QfVXperjBMV+9N2gSlFshgYfWgTXWWSOKgczONcS8zLyncF8ZZIGnDWXsihff5hpnFm3qD6KMSE7GdxwwIKpjUPjbYUNaoZNDnsNsLy4sRQ==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rails-master-key 
    type: Opaque