apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rails-master-key  
spec:
  encryptedData:
    rails_master_key: AgBXtRnPPtyv0V3eF3dL2a0/VH0wJPDgv3xkHnAcnT6oF5ANrwBd1SJakB1EzusEzjAf08TDZWKvfVzuyCVoWB6V4JAIIdU5jeM1yriskufnOYUxD1uyPVJWGluP+Q0pZniHB8ZjbrBi5whjVDcCrhjKfWSsw71I6r/dGv093kLFLsihxbV2bw3ONqcwcLOzRjecLnmZAoz+06RcOMFPxdpfrxtlCLjZG2m1J+NTb9csRFNsLtqIkZ9YPgloarAfXdQVpdpFgcwK/0XyntC+xBoiajzw35c4m5wb8mA0ge0KneW8EjhgIlh9DgQMnRwtfAstfF3/n8cXbV6oxQ4s8ufme2qKoTLXeufnaZKFsJ6mTMSvSG/h1YH69kLe76FDV5ftt+tyiWYScOq0GjhmOC6RyS3rJmAaVWTr8bfcoSifFrYd2dkLeNuZrRQz9t6MnlNnXNnY3GmOonWTHTGyWYiR0CbaW/eQ72QWaOQJHHy43nbRlHxYd9KAOtVHqK60tsegqmTejmF2NkigScmWCF1GMG3NCD9YTU4CPKnaoMmlkOgIODntbv1nAY4K9n4MYA62fu7TqFwj2aY4DqhfqXxbL6YeoC4yAn4DBLEW2hr2BKAQxlFfVGCb8rFHj+cSsCWqvm5Yce5FmsiZCVwSQ0Pk40s5MFIMisdl7JvHrfdg8x+R5xFYTJabwUSWE4stLFV0BUw/SoqDcLUKd8n2ZuAXmX6+RuNNjBTiaH/ydLd53w==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rails-master-key 
    type: Opaque