apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rails-master-key  
spec:
  encryptedData:
    rails_master_key: AgDJCo43oM4KEHbbRyBBoUbQ1/9iBiGHyzor6HH+3SZMWv7c2zn0IwIJU7g3Vnv1+1/YyntnWdeuBEAsCEWP4oIISraUx/3EPNJW/vvwrgc4dXaZ1AX18y7L9tX60+ABiMuonNAocA9sWieqGA4eMNMxmnBvRJUyz9ImOsFM5x/1Rq+GLLriC8PK5Kkygzqop23YuPGw8z54+qKECNt3ZlLf2PLZPc1THUZfPubdBPPgk0f1Kqg3Ci+wKelIEBd2V9YFLOlddv5lzVPk/ljEeYspbXoFE6qgR7D7ncybOYvE3b/2x/8pBPtO+hn26F/QS8tupZBvCg7BzgDigWl5RZsm9+GwDAdSUmwLj756SdRI3SCYSnatuPkjSsdGg0pa0Qw0FxJw//v9k7IYOiQE6CtNph7dPMQhAndYNoQjP8WGbXDetQ+qdNC9KOLWuFZp1f9PBUz6RUk4AeTiQ22P8NR4bTat249GF1sHlKMviu5wv/kEE2jd0AV3W93RuFlGfNed7Ph4zs3mwn15WrFSAO16n+MOSPY2diD1f6dI/n729g1NV6gX5eI25MHB2Z6T02uIYZBjcjLwGSQPqWyqccZ5IogeUJQYwVcZ1C5yR8G2gEPyYKnjt6W9demvZ4YwuD4rmRC5pL4o0lPRgRtbL4EP0EEd0fjKDYbvNL5TN9/XfqF8NqodfeujM+jdnU/wQEDPeGzzv7m9Sh7ErO4Pd6bhzGiLHBPjWj1xwJVYcnTnbw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: rails-master-key 
    type: Opaque