apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-production-uri
spec:
  encryptedData:
    redis_production_uri: AgATLGk/pbD5xAx6I89ukAVqRnyJBUrrhiAue4muSDrSka1iUkCHhwdMuwMOdB24MPlRkYX8KpxbAuFuEzL7FUa2qM5wQ82cUVYcuAEwCxqFlQTimzMYh21pZnasxLIoVuxWW8owPvJhwfpPcZ6xPaF+DBZ5pIZAnsJ0oj5vM/ZkcIoRiehXlcBpAzLvJqRhQbJXJG4tXac+pM3qlzIqME9uRdzd7UmLhZIz9eMbUH6cWB6QlhV4M+2Yz5QZOS15XydeA4R1jFgTxzQlMeoFr+GIPBCfQYraCkZoIOAKbAGEKAryuacu23jbHcVhMUu2VKZNHcUwPDJMkdiv6X9J2hwwKz3/b5JTs3tp1HSg3bqta4bnOiq5YXU+uyXnu+Aqh6YN2i4MNrarW7pbgA+6pI3pvrRyqe6QDsWEVr2lu/HCLCJdfOB0WxZQk8RnovozHUx182nOV9bwYtcKrf9lhXbFyNund/b57VNFOPNquZ+jDXRJjV9SQp4OveXleowKFY3C8jh6cOVY7kAbG7LH7AFN/5D8msPIqFSU0wm1Lq0XEMXvf/YYMb9asmXscI9LqLHPBvps3Bux0hehTnZaNXwRzJMwr2tJA2qiqoPYDVZZpAgWSlcHdf8E9QUwz1M/HTPXQ1xbYz9BrK7W54CM0wTN2u7U3klX3AFecf1xTfMHa8M+uqv/7wJkrXFs681/D69RXW4jvRrKYR+rERgLXFOL3Wajp2sVLPJEKGiGZofrPfVDkxTq345rTSErbC81t4UoOb5fLGHv9iU7VToVxHB/ndZ6p77RmxLtXvSibWxRUmAaxDtmtxQPkUTq
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: redis-production-uri
    type: Opaque