apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-cred
spec:
  encryptedData:
    username: AgC1uWZtkTwsFa162buvwG9UVFjAaEU8LWLYuHfuhY4qM7dWU55o5V7Vm1tL+WjVoetw/kohs4JulzhK0elC+tGqM8jHiWEvty21MiTl+aJTbiy4zAX3ZhyYyU8flSa2leAkskgbvCRxT254W2kPQgTHwCvrAgXqmrAc3dr8b4n5Rk7i8esSSrTRpSJPlyEflz86r01/bQmj8BTIqlUhTRYKDsxejNaUIgMOjZlUDuSBGRkwGtROqXB1OO0bjrYQo0bwSFlPwVQ6mvzk2etruomwQ3ATcjScYA5Rz2Qy+L4LArnVSZcTw9K0ZH/2W6T+EECvHDHkXQbDPVcDfBpHYIw4CkWArz8NQKhhXnr5koJCMUDqawKPArpyAoa6L/T2urkMW8Ea88KrZQJraQ8bKlauJ2cEuLIOsteqKtr/KgBoFZDtWBpCeq/OLQhWlQAHlaACbHlorkvJjxp3/JX+LJgcJbrAl7lRVzUwBEAFQQf3vXskBqrZz6fHLXKS1FF7YsAmkRr2EA/LGc2ZM1s3f3kevbmvhKTvEFCRDcLF3IqsnxfkFEp8ZIjtJhHHn2T430+zu1cv9WEIvl7H6YZ30KIrz0DyQgqKej8blOTUMPwYcHnub+v0paAcnAajEGAZsfEpWs86Pzti2czEV6ADv2K4ZIZ2iNW+uHAy89p8FFXswGzHK1UOqV1mz5NDVm7oqWgx07f98w==
    password: AgAi7SZcLZwyKS6B9nr1WiPUzcxpWXoaexac0vvSxJuKM2RtEzz3cwZNCLxT6BPcD0LwVP9HUgn0CTal9c4MkhvD40abALcNvyZZGQfUKgPAEPYYrZAAUvBmEPK7JeHRlTNmd2ABxuMB312hcG2l70Mwyw1DS3qMV2e6xyJFmUnAiarKtFiEiw7cnZdKNn3vM/U9fI+3Y+E82etpScq7ySjIXXt/PJWqQIj48HdZYTgILVsstluusvdwtBiqNGmQnX9gj3HYdyJf36odiSUhhA9TbGnuCKrjYRiwUkTawDnjhxk5KzlB9l57oONfjGHWmd2SKLhtwZvylJHJvwmG8rw1wfLqU5GKHfZzoxFMXjWV8c04V2zFwcLGhxP047SNLbE4wZNcsN014+SE9HUYxsU4jCY9LKIaNQDxS1siGaG3TrIXY/KkJu60vTumoTILtQUfay8NKORwGAoCKHKWd75q9y8on9AN3uPr5kKwnCNDA1MtG0FLGrvyda/Yv9WNQBNyIZX3HZBq4ScpWCnwFY/6KehtKv/egglEyvSzPDs1lWYtZyO8lA3H43OnLskjuJUME1UbfyldFIvfoqVrzzjAoHXOvfwZKlCXFiSzhkJrjYUb3gII6s1ByaBQgJmeW6QEfMauReNNl7ONIdblR5OVuAAHtH+HWQldtEYXSQPaJ+ELopskb3v7pnboqi8QJ6LX/137jGnvDjo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-cred
    type: Opaque