apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-cred
spec:
  encryptedData:
    username: AgCDFO+cN6oBH6CtgadjQ7Tgf6Ttp4N0qxGC0gp744i4AszLhN81UD2pgtsWyxF19cSM+2R/gXC+xNEBbb+CPJC7YafjBBQLgta/b+Qd+kug2NKqS6eYg0sZNBmmwgZOXCbz8LPNOetl+9RkB0ADpdLa/4OB5fPYmDIv5JvfkEaixMN9rZ/pKVbLUrmT0nbRAuF4J3eGbwwp63GTWAwvRrZ3F4cMuYYeHP0uuegO/AUPVZJGhwomMj6kG6X83s1OfJqAc/ue2u1UGB3avTxVgzhM6OqRw3sjYxi93EoDxF/r2HNqf/ZV7eFkMrnReznYx25JX7rbhWNHMSmlfZyhomFsrQeNJ1Xwbnc8jIFHlK9gPde7B51KzSJr7Jg7RP0W56ZzeAKK9ttmXvSR2dDtr81i385Eaoxl7sBy1+EFL2LX91GBe09cEjlnH/7oHhtQrNqj8zbxtQnSrlvwbMMKr2qG/l+3tJnOQG76pLgxOlsu9qQXPV4OXksEaEdYSUagh8TcnkhnQBAz53kr6juYTqtCvVhHU/BTe6wpRn19Xwi5C/JSuCVCtag6FmfOlNg70PyQo6id5OwpJP6FTNKH1UKWxlCzoiEnRDERFbyqK1VxB1PuMHpP7otn0JyzdKEfD9THXKM9mbB1QqNeMigt5teCkc8sERD7RnE+ck7EokUq1FFk7HZ8p0VjzIDNtFaq+A8jhlQMog==
    password: AgB6C9BeZOs1VbZw2KyV22gpYpe4f5dzs9h1c07lgN5DU9DG1uVwxMgUb1ZcSdWvN1H5ZZ5YO3ttvI5CbInv0T/1ZonA69mLkzRA2V6azKVtlhN2+8aYQ75QEs7x56b045CmjqUK+wX6bYCDP9z1ZYAHV0wJyDF0lF+DwtRultPkgjuXVB8+4m3n9LCvnem3IDprGS/HpccHOjFU4XbJIjBUIvaR2i31o4+gFHJqZwzjML/pZj3bnK67Fj+6/v612pSf8OOKGhfuG5dSNkCFTY8/tRh0+tG1VT/0ENFPan9mISgRPrWCbZG30BXCYpiss9erGb952BAqwQ27N+4ChZGGfmi0nrE5JtdWYIYqTGIDiJ24nCXN6kqibIPS0fLXMaw8okkY64IEOxjaFCzPPvbMpG9W5brL8J6vuCynyWdpEXbenfRs9UrrNymJfSil/1fgap9xhmeB28DW2XMszRvfihQ11TftLxkTK5ztYH5ymLeBygVcVfC2GxAn/7fuc7YCSe+xLd0ibKsRwuYMtQD154eq7EFJe40b+JlWS4d6alJCZ//0xOjyQWAi75YO3FBuopSVcOAY9g7+7yFgu7Aw8Ge9bKVaVgERsLIaHw+QHCZYLBqWCRX5FsLxwXiDAUzx9YBJ5co3BDpRtrU9ojG6oYelRp8D+/A18felEv0fr22Z7r2fwFf33AJW31w6mtsGs26uU+W++dk=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-cred
    type: Opaque