apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-cred
spec:
  encryptedData:
    username: AgCXG/nkoZOMsyffFBakOT+ur2anDYvuHWE7WPNXVi61+BZfSITmPBZFzbZ94LLqOkJrCv0ko/vMHovc3Z9aI60dtPj8r8vLg6DshS2E7Qez/JCWoilfVuNHc/2J1fkCsb9ifKC0mq1GN56vb3RU+u0t6cmju/q0nULo3knpvVt03eOrJkoYkM4fhA/LTRtH9Wotp+LPIUW34fR+HY4QCfFmrOyweNuLWbQT1q5S0c3Xrxpw5Da8SyFXEsrNBTrd3c2BHxwlhBfutAgVmaTV5CjUWiAoDngLs4PhrmvCg3AXnrp6vEGOXu06XlN8rz1KzzYbpAWTP8RheimLG8hwyHa52lD0C52+SYs7I33KMeQTLoiErsLDXLQemx/O4vBa/PiXfZh0pNLMPid5KEkiWq5MVZVpt6l4glyNe6YNewqf+DxgxG178E+pGkQIPJkIcWmMpk5v8s9MFm22WzKbK91g0zFpG1XukmSK+yHYDg/FIRb5leQUt5VfNZsckcIKH65sCRrTpgzOq/u12uGgyW72QBQT+KAoqWL4DK0OewMhPGKP4GoyYSF4RPO6vP2gZncGCqUoQLCZrUCOLq7g+ZwwyqGV+6J3pVfkaraf4mfeMxzdxMrZxJiIs3A0BBZASE8w8XPJSJDllqq0zhWUpcDOfxER4DnlfJs2tGHYDwLuN+vPkyPUfHQOKc1MnoxV+/B2AGC6qQ==
    password: AgA44BsyIhN3k84i9N+Ul5xA+lZlgDATR595zWRX0kUgahntGFU/Y2KsK4muj5ttWyxiSH3hvHofrdOCiCpcC8DpIUU0JVGdqYDlilX1kOEDjGJXRDIfqfWm/l1lPra/zjZ7/A1eOxMgudzzS6hvuwBCl8qyNUlSEWTm3MX2iXM5D4xcRz0ym+X8W21m8fRnfri/m/UzW/FQShH3ZPhlbEvcfm80P14OvSzxwtvhY5yT4C5sXSAuql+tK3W5BE9S43ubYFWXmZjUZGaP63VoApzHj8dKE+wOpPwq42ib/4hP2ss/N6NhP4u5OCxZA+aRydoPQ+xlSEagVIlaH0qhwPQt4dQsfjYpAQpsAlXO1mn1HxyA33IxRyvc6rFzcvPholOkyAThyzjLPfOwIuvDjSXuIzUlbwT4nyl408jD8vgIH6T1VBIZawbmuzHlijJVfvXnMD7EQtwv39sRqw38jxfayt5qe/mQJeaR+M7EMnSOlREQQcgUUffcze6cYc/Q+5jU0puuJzJCLIfZe8f9g6ZT/rVBkRI2yNTXmJ7sDSlh79DnSwJ5V3Z5s60wGzGqhNI9ckIeApMXTOF4Nuel+0M42EA32QY/K1xfWTI++6y8HurcFI3vsaL3JO8swVkqkvpwl7z/ASDe2I00Rybk4mx8FsqK9p6cOQCxOjXuxM7Ji5J8/DRiuWcNuYKNMfVCsUJsfs86Llbd+jo=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-cred
    type: Opaque