apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-cred
spec:
  encryptedData:
    username: AgAbGuG+azHHxKgACE8rg0rc7i1BYQQOAmokesuaNSY/vSD/Yt9LQda5jIyzTN5xWxnjHGQLyVMkVYA+Q1wW8LwuGrZaIHyiLdWf/eVt8XEo/YaA6KYD3mZrqQmbeKIgK9/j+ufdPZnHStfPsokbR0+wBeEcme2QwuW/vYekov231yc1knQwtcTxRZnpOZ3C06LgjGIM4ayjAJIftaqF7hDJ9IRm15r+0WmgYoW78x1rVULFhn8eMXr+h8WeYSGOd75uT2LqjLoqnwpja1aSmOctaeCJ5k6E3o14pJN0jQJR7D6t+urPdnkffEnaT+4hOlgFgD/V5cP2AvwLCsfxfJ6tjTVtbUxvjhcAp4ZtABxeeYJr7BQO2X24uY8xE4F7Tdgth+OW6YFpT5vLxFv+fb2rGGzJaz6FJY81v8YzkXpyv0mFylyt/3fgOsxUW97Qd8AQBPIwXoaQ9oz65zw6C2QGGks3qlCcApD4wPQ58iVwwaSyD0odvX2jIcHbb2QuX9QWn7m9K0gaY7z7VCHveH9qAKFMwuCFAxxtI7/sZsNri5D8JPQjTTF28jFha20eip9zvAKGLHH247yFqOqHivoHpdfwB1J7TjHud7rObaMvxD/mAG+njjMK1gCtu13oH0yIm7qBtl6IdHargn8HzXf7a5UT4ysfjFV62zHqYjvyFEseJ6jeGxC8wtpUa56/V9Si8cayDQ==
    password: AgBrPIZEiJdWzjiElMnRIvxuy2IwbKmYLDFycyrTX1dQWcR0NmoUJMpCllZxdpnsvE7cbbTECweoU7Cez/B7Ugx4YMvXydubuteg4ViAAlljqN0X2NmxbUDd1n/Ux9IlzhtvXH15kcKuxqEqa7reV/jb3fjyHDswz80qBQM7U94Jl2NluNJizu00bpO4iPhaWrmtToJJTTjVtKjlp+TKf+rJDyiJCGN0fLtwFQsyp75DcrVnTvFc51yL4F1IqgXv+anPi52ichiruDDxUj/NvuqDAAhPnyqyScXOXmmeE9JeOZ5D3ZCOiV1sxVc7+TwyxI7wVVmvlwled64QhQcuJ4tjJxiuM+CnAJ7mJbKdi32P5eBU86oVPJ+dpfu2jmd6yWmYVOyRlYF7hxuGK4VYx23w21U1hNEGXAkA4aBqX6GYNZT2asd+1NlUKQ1uXRaEA4Y06Jdz+aUkOQ6RuI6PwL3/h8kUSaCgJlQUbjg34t6kQ085JocAehMk3o0qZEYz+x3Kb/i7l7Wzrf/6Boj7vummdFuTpN1709qs+IMPbsDKFm7PfKU/PJUHT4RZlGlviYPdiaonW70a7D2XU3sMPix8VhFbfmgKE1lRRSJo5WUnxyg82AT68JYqoFYBgPEakb9X4HEEFNWTEivFuxEAKYhm6MiWYMCyDOsG+ubEOh+xJ3DJyPbGv3wfkYjVyDUyT9FI/Dmmmd2SR8Y=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-cred
    type: Opaque