apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: test-cred
spec:
  encryptedData:
    username: AgC9SHQXvf2l688+H4UKe83jvmLLtqEE56rmanPl34JmErt3LsU3ezGZRYoBHNKEs6rB5iNFN0M4qxeIG2PhC+23y8DGcKRnUgx3LHcAIOysG4B8cJGYt6GElvp+lS/JLp+r03TbzmJIXx6JjgeWHDTcTc/mFEtuMhurnA+mTUADZgInx/gt0VGPtRyuIw9G4/FUwUDjjt/nrluviuM5Cq+y2lta/UzZbeKLynHzoO4ydozdBNjM9442KijlfxNrqhlLfga1zpObr94d+4tWSH4taev9ghMDmOi11cEg8yrntDXwAn/LQ3Ygp40TEK4UnoloEPKCI1ssmuRA+feHxQn33EFYXywhc5qTZ9l8WkWHZ+wYokgAlv2mxkcgerCUkuACEFN34RyQbozctulcMtblcoU8pBuIZ713yIeNGKvAH42JkyNhZ5R1UaROxLriq33slc9j6kqqfH/lQ2FWm7A9VJW+vcX0Q4181DLvk3BBTx+1ik7VrqZunQ8dvO8hESrpzfktbEbQ3Au1DRHzXA5WyqMJTyflrBil/c39TyvM+QWJDiu/m2Aund0D9A3mAffbwdKG5xhD/LFvQwJnhTylJxJecDL+YvE/bDAXndEpuNPhNAVcbPLdwV8T58usIuhnws5ekq0E177yEtdn1m1qHQS63Pq14XmyEQ8ynxNl0Lz6vSiIONZo76RkJeY+LT/HcEFDhg==
    password: AgAy5Jdkvy8pe+oNvgLgbaWoZFhp/QngXpZHJNsWBrfRkPV1sT0i9ZMv3H1zVvIlmhUkw490nZQxKXYDNNF6/N5J4Dg3LW2PAdcjMcLrfGz9laBnB/B1ArrXHfgcjkZnbmMpS3Emi1cA+oF8pw+l/J1bqp9VwpDXbkPOwr01xKXvKuH/Tmo38S2CrDRn6rQzhsofaoPDxRmz0CKDaVR6O+dfslmvwKKtMvdhuHSDO2FKs6yaMdQd9fEd0E7+7XcqcldAhlCJ907wODVO9X1zhQIASr4fi37RVTFfiQ4eEs8OD0HvRtlT7ke0VhLAIjuMnA7LnrvMaxNxlMOq9CYtezRrwmVywK5s31SALQZZtmquzDYcZmHaaokY3XzpTCi4jkdiu66PlWGdtnzxnA403GUXyG3X3pzUQUTpgPEpgqForvZLw5EXSSmdNQcCaAi49WrQH/OHpUnBrvwj+i30IK9sSPxyGD5COefhBhdLByjuuEmTxKgZg3/FkTSiVYSpOMC+wt55JLiz+nMp7q/l2wC/BJKZHwjFxR5aIX3T28ByvuUwzewPW/nNQjHFWgsH8NNqroPi09pPvl7Qzh3x8UFFJ69nf18WBlTaF0iXpuiM4V+ke7zRB8w7pddk4U+8qEJIwdR6OaZmmnPolMGkYMzN5esRhaJNT6bbAVp48uARK3A2uuNCHVGv/CsqpUFLJTLak68o8BoOu8E=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: test-cred
    type: Opaque