name: Copy GitHub secrets to runner env
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GHCR_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Store GitHub Secrets to runner environent variables
      #  run: |
      #    gh_secret_names=$(gh secret list -a actions | sed -e 's/\s.*$//')
      #    for i in "${gh_secret_names[@]}"; do echo "$i=${{ $i }}" >> $GITHUB_ENV; done
      #- name: View runner environment variables
      #  run: env
      - name: Store GitHub Secrets to runner environment variables
        run: |
          echo ${{ secrets }} | jq -r 'keys | .[]'
