name: Copy GitHub secrets to runner env
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GHCR_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Store GitHub Secrets to runner environment variables
        run: |
          gh_secret_names=( $(echo '${{ toJSON(secrets) }}' | jq -r 'keys | .[]') ) && for i in "${gh_secret_names[@]}"; do echo $i=$(echo '${{ toJSON(secrets) }}' | jq -r ".$i") >> $GITHUB_ENV; done;
      - name: View runner environment variables
        run: env
