name: Copy GitHub secrets to runner env
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ secrets.GHCR_TOKEN }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get all GitHub secrets
        run: gh secret list -a actions | cut -d " " -f 1
