name: Copy GitHub secrets to runner env
on:
  workflow_dispatch:
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get all GitHub secrets
        run: gh secret list -a actions
